-- Auto-generated by scripts/generate_lua_data.py
GoldMapZones = {
  EK = {
    key = "EK",
    label = "Eastern Kingdoms",
    dbMapID = 0,
    uiMapIDs = {1415, 13},
    bounds = {
      minX = -15025.200,
      maxX = 3492.420,
      minY = -5613.110,
      maxY = 2531.255,
    },
  },
  KAL = {
    key = "KAL",
    label = "Kalimdor",
    dbMapID = 1,
    uiMapIDs = {1414, 12},
    bounds = {
      minX = -11918.300,
      maxX = 16320.200,
      minY = -7947.520,
      maxY = 16243.600,
    },
  },
}
GoldMapData = GoldMapData or {}
GoldMapData.Zones = GoldMapZones
